# This is a basic workflow to help you get started with Actions

name: Some Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    
jobs:
  checks-actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.1']

    steps:
     - name: Test set-up PHP action
       uses: shivammathur/setup-php@v2
       with:
         php-version: ${{ matrix.php-version }}
         extensions: mbstring, intl, pdo_mysql, redis
         tools: composer:v2
